### ISSUE TITLE
User login/logout system

### ISSUE THREAD

**Issue by taoeffect** [taoeffect/mileposts#1]
The primary branch for this [milepost](https://github.com/taoeffect/mileposts) is located **[here](https://github.com/taoeffect/mileposts/tree/master).**

#### Description

All of the tasks necessary to make it possible for a user to log in to the site and log out of the site. This includes modifications to the user interface, so that means we may need **@dan** to make some new markup for us. It also requires some modifications to the backend so **@rachel**'s help will be needed.

#### Files
- Create `src/backend/login.js`
- Modify `src/frontend/login.html`
- Create `src/frontend/js/login.js`
- Need to create new login/logout icons and place them in `src/frontend/assets/`

#### Issues
- [ ] #29 - Backend database user schema & API
- [ ] #17 - Add session info to database **(shared with MP #50)**
- [x] #30 - Clear cookies on logout
- [ ] #28 - Frontend JS for AJAX login/logout
- [ ] #45 - Markup for login interface
- [ ] #44 - Create backend unit tests for login/logout
- [ ] #47 - Create frontend unit tests for login/logout

**Comment by taoeffect** [comment]
So **@rachel**'s working on #29 and making good progress on it. I've almost got the frontend js working, see the latest updates I posted in #28.

Once I get #28 closed I plan to work with **@dan** on integrating the markup (#45) with the JS in #28.

**Comment by taoeffect** [comment]
**_Normally you would not lock a milepost, but since this is being used specifically for illustrative purposes I'm going to lock this issue. Feel free to open other ones if you have questions/suggestions etc.**_
